const IMAGES = {

    LOAD: 'IMAGES_LOAD',
    LOAD_SUCCESS: 'IMAGES_LOAD_SUCCESS',
    LOAD_FAIL: 'IMAGES_LOAD_FAIL',

};

const STATS= {

    LOAD_CAROUSEL: 'LOAD_CAROUSEL',
    CAROUSEL_LOAD_SUCCESS: 'CAROUSEL_LOAD_SUCCESS',
    CAROUSEL_LOAD_FAIL: 'CAROUSEL_LOAD_FAIL',

};



export {IMAGES, STATS};
